version: '3.7'

services:
  server:
    # image: mrphillc/agent-vs-agent-planetwars-server:latest
    build:
      context: .
    ports:
      - "8888:80"
      - "8995:995"
    volumes:
      - data-volume:/home/data
      - games-volume:/var/www/games

volumes:
  data-volume:
  games-volume:
